spring.application.name=EurekaServer
server.port=8761

# Estas dos líneas evitan que Eureka intente registrarse consigo mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false