# 1. NOMBRE Y PUERTO (Cambiar en cada microservicio)
spring.application.name=BoxHospital
server.port=8083

# 2. CONEXIÓN A LA BASE DE DATOS

spring.datasource.url=jdbc:mysql://localhost:3307/hospital_box?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. CONECTARSE A EUREKA (El jefe)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true